[book]
authors = ["emdneto"]
language = "en"
multilingual = true
src = "src"
title = "OpenTelemetry By Example"

[output.html.fold]
enable = true
level = 0

[output.html]
git-repository-url = "https://github.com/emdneto/otel-by-example"

[preprocessor.deps]
after = [ "links" ]
command = "python scripts/processor.py"
