[book]
authors = ["emdneto"]
language = "en"
multilingual = true
src = "src"
title = "OpenTelemetry By Example"

[output.html.fold]
enable = true
level = 0

[build]
create-missing = false

[output.html]
git-repository-url = "https://github.com/emdneto/opentelemetry-by-example"
edit-url-template = "https://github.com/emdneto/opentelemetry-by-example/edit/main/{path}"

[preprocessor.deps]
after = [ "links" ]
command = "python scripts/processor.py"
