[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "sink"
version = "0.0.0"
requires-python = ">=3.13"
authors = [{ name = "OpenTelemetry By Example"}]
dependencies = ["oteltest", "flask"]

[project.scripts]
obe-sink = "sink.main:run_sink"
