receivers:
  otlp:
    protocols:
      grpc:
      http:
processors:
extensions:
  health_check:
exporters:
  debug:
    verbosity: detailed
  otlp:
    endpoint: http://localhost:4319
    compression: none
    tls:
      insecure: true
service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp, debug]
    metrics:
      receivers: [otlp]
      exporters: [otlp, debug]
    logs:
      receivers: [otlp]
      exporters: [otlp, debug]
