name: MDBook CI
on:
  pull_request:
  push:
    branches:
      - main

env:
    MDBOOK_VERSION: v0.4.44
jobs:
  test:
    name: mdbook-ci
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install latest mdbook
      run: |
        url="https://github.com/rust-lang/mdbook/releases/download/${MDBOOK_VERSION}/mdbook-${MDBOOK_VERSION}-x86_64-unknown-linux-gnu.tar.gz"
        mkdir bin
        curl -sSL $url | tar -xz --directory=bin
        echo "$(pwd)/bin" >> $GITHUB_PATH
    - name: Run tests
      run: mdbook test
