name: Python

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
    paths:
      - 'src/python/**'
  schedule:
    - cron: '0 0,12 * * *'  # Runs at 00:00 and 12:00 UTC daily

jobs:
  snippets:
    uses: ./.github/workflows/snippets.yaml
    permissions:
      id-token: write
    with:
      stack: "python"
